const images = [
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image1.jpg',
  '	https://fec-images-body.s3-us-west-2.amazonaws.com/Image10.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image11.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image12.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image13.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image14.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image15.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image16.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image17.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image18.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image19.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image2.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image20.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image3.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image4.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image5.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image6.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image7.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image8.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/Image9.jpg',
  'https://fec-images-body.s3-us-west-2.amazonaws.com/funnyWhiskey.jpg',
]
module.exports= images;